Repository eclipse-zenoh/zenoh-plugin-dds, pull requests merged in 2024-10, with the labels that each got.

#351 new serializer API Update
  Cargo.lock
  zenoh-plugin-dds/src/lib.rs
  zenoh-plugin-dds/src/route_zenoh_dds.rs
Labels: enhancement, release, internal

#356 Updated Zenoh subscriber declaration to undeclare subscribers when references are dropped.
  zenoh-plugin-dds/src/route_zenoh_dds.rs
Labels: bug

#359 Sync lockfile with Zenoh `3740564` from `2024-10-08`
  Cargo.lock
  zenoh-plugin-dds/src/lib.rs
Labels: internal

#361 chore: bump zenoh version
  Cargo.lock
  zenoh-plugin-dds/src/route_zenoh_dds.rs
Labels: internal

#368 Update cyclors dependency to version with unique C symbols
  Cargo.lock
  Cargo.toml
Labels: bug

#370 Revert "Update cyclors dependency to version with unique C symbols"
  Cargo.lock
  Cargo.toml
Labels: bug

#372 Pin cyclors dependency to version 0.3.1
  Cargo.lock
  Cargo.toml
Labels: bug

#376 Updated cyclors to a version which mangles C symbols to allow different versions of the library to be loaded in the same static binary.
  Cargo.lock
  Cargo.toml
Labels: bug
